### ISSUE TITLE
Add option to build AAB and APK the same time

### ISSUE THREAD

**Issue by mateherber** [bitrise-steplib/bitrise-step-android-build#24]
`*.aab` files cannot be installed to local devices and can be distributed only through Google Play Store. For testing purposes our "Deploy to Bitrise.io" step generated an additional `*.apk` from the already built bundle so it could be installed on devices. 

However this approach had a limitation (the new `*.apk` was not signed with the same key the `*.aab` has been signed with but a debug key) which caused confusion in a lot of cases so we will deprecate that method and instead we'll let the users build both `*.aab` and `*.apk` in the build step https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/93. We'll make sure sign-apk, deploy-to-playstore and other steps will handle the newly generated apk and aab properly.

This way we get a properly signed `*.aab` for store deployment and a properly signed `*.apk` for local testing.

**Comment by istvankovacs-bitrise** [comment]
We did an investigation based on a user’s suggestion on this [thread](https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/93#issuecomment-762383999), and we can confirm that the _Export Universal APK_ Step already provides the capability of generating a universal _APK_, so there is no need to introduce any changes here. It can use the same certificates, as the _Android Sign_ Step, so the resulted artifacts will have the same signature too. You may find further information about the _Export Universal APK_ Step [here](https://devcenter.bitrise.io/deploy/android-deploy/exporting-a-universal-apk-from-an-aab/). 

However, the **_Force generate universal APK for AABs_** option of the Deploy to Bitrise.io Step has set to **FALSE**, in order to avoid to re-generate the previously created universal _APK_ by the _Export Universal APK_ Step.

Given the _Export Universal APK_ Step, the universal _APK_ generation will be deprecated in the _Deploy to Bitrise.io_ Step, and we already put it onto our roadmap.
